### ISSUE TITLE
GPU Used for training?

### ISSUE THREAD

**Issue by Aldo-Aditiya** [mobassir94/comprehensive-bangla-tts#4]
Assalamualaikum Brother, thank you very much for your wonderful contribution.

I'd like to ask you - what GPU did you use for training this model, and the batch size?

**Comment by mobassir94** [comment]
walikum assalam,
i used NVIDIA RTX A6000
Graphics Card (48 gb VRAM). for batch size it depends on model,check my training notebooks that i have shared in this repo already. for training vits i used
batch_size=104,
eval_batch_size=48,
please refer to this notebook -> https://github.com/mobassir94/comprehensive-bangla-tts/blob/main/bn_vits_tts/train_bangla_vits.ipynb  thanks
