### ISSUE TITLE
confused about phoneme

### ISSUE THREAD

**Issue by desis123** [mobassir94/comprehensive-bangla-tts#5]
First of all thanks for your comprehensive bangla tts. I am trying to train a model based on  ViTs model with phoneme [last updated one] . When I downloaded the dataset from kaggle . I have found a model for phonemes inside that archive . But while going through the code I have found that phoneme model is not used in   notebook rather phoneme is called through VitsConfig . my question is 

will phoneme come from coqui or do I need to use that phoneme model [found in dataset folder] manually . If I need to use it manually then how I can call it . thanks in advacne.

**Comment by mobassir94** [comment]
phoneme comes from coqui and i have used espeak-ng already. 
inside vitsconfig these 3 parameters are related to phonemizer

text_cleaner='phoneme_cleaners',
use_phonemes=True,
phoneme_language="bn",

and here the phonemizer gets used :

tokenizer, config = TTSTokenizer.init_from_config(config)
